---
title: "ResearchPoster"
author: "June Ro"
date: "7/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

getwd()
install.packages("dplyr")
library(dplyr)
Japan <- da34969.0001 %>% select(water = J2Q29, sugared_beverages = J2Q30, vegetables = J2Q31, ocean_fish = J2Q34A, high_fat_meat = J2Q34B, bp_diastolic = J2CBPD23, bp_systolic = J2CBPS23, hemoglobin = J2CHBA1C) #eliminated 'fruit = J2Q32' for the purpose of merging datasets
US <- da29282.0001 %>% select(water = B4H19, sugared_beverages = B4H20, vegetables = B4H21, ocean_fish = B4H23A, high_fat_meat = B4H23B, bp_systolic = B4P1GS, bp_diastolic = B4P1GD, hemoglobin = B4BHA1C) #changed 'fruits_veges' to 'vegetables' for the purpose of matching variable names

head(Japan)
head(US)

US_Japan <- rbind(Japan,US)

set.seed(10111)

x = matrix(rnorm(40),20,2)
y = rep(c(-1,1), c(10,10))
x[y == 1,] = x[y == 1,] + 1
plot(x, col = y + 1, pch = 19)


install.packages("e1071")
library(e1071)

dat = data.frame(x, y = as.factor(y))
svmfit = svm(y ~ ., data = dat, kernel = "linear", cost = 10, scale = FALSE)
print(svmfit)
plot(svmfit, dat)

make.grid = function(x, n = 75){
  grange = apply(x , 2, range)
  x1 = seq(from = grange[1,1], to = grange[2,1], length = n)
  x2 = seq(from = grange[1,2], to = grange[2,2], length = n)
  expand.grid(X1 = x1, X2 = x2)
}

xgrid = make.grid(x)
xgrid[1:10, ]
ygrid = predict(svmfit, xgrid)
plot(xgrid, col = c("red", "blue")[as.numeric(ygrid)], pch = 20, cex = .2)

beta = drop(t(svmfit$coefs)%*%x[svmfit$index,])
beta0 = svmfit$rho

plot.new()
plot(xgrid, col = c("red","blue")[as.numeric(ygrid)], pch = 20, cex = .2)
points(x, col = y + 3, pch = 19)
points(x[svmfit$index,], pch = 5, cex = 2)
abline(beta0 / beta[2], -beta[1] / beta[2])
abline((beta0 - 1) / beta[2], -beta[1] / beta[2], lty = 2)
abline((beta0 + 1) / beta[2], -beta[1] / beta[2], lty = 2)

rm(x,y)
attach(US_Japan)
plot(x, col = y + 1)
```

